services:
  turtlebot4-discovery:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-discovery:dev
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - SERVER_ID=0
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=11811
    network_mode: host
    ipc: host
    restart: unless-stopped

  turtlebot4-simulation:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-simulation:dev
    command: ["ros2", "launch", "turtlebot4_gz_bringup", "turtlebot4_gz.launch.py", "use_sim_time:=true"]
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
      - ROS_SUPER_CLIENT=1
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw                    # GUI related
      - ./turtlebot4-simulation/gazebo_data:/root/.gz:rw    # Persist Gazebo downloads/models
      - ./turtlebot4-simulation/rviz:/turtle_ws/rviz:rw               # Persist RViz settings
    depends_on:
      - turtlebot4-discovery

  turtlebot4-rviz:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-rviz:dev
    command: ["ros2", "launch", "turtlebot4_viz", "view_navigation.launch.py", "use_sim_time:=true"]
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
      - ROS_SUPER_CLIENT=1
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related
    depends_on:
      - turtlebot4-discovery

  turtlebot4-workspace:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-workspace:dev
    environment:
      - PASSWORD=student                   # code-server login
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
      - ROS_SUPER_CLIENT=1
      - NO_AT_BRIDGE=1
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: host
    ipc: host
    volumes:
      - ./turtlebot4-workspace/workspace:/workspace:rw
      - ./turtlebot4-workspace/code-server/config:/root/.config/code-server:rw
      - ./turtlebot4-workspace/code-server/data:/root/.local/share/code-server:rw
    depends_on:
      - turtlebot4-discovery