services:
  turtlebot4-discovery:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-discovery:jazzy
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - SERVER_ID=0
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=11811
    network_mode: host
    restart: unless-stopped

  turtlebot4-simulation:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-simulation:jazzy
    command: ros2 launch turtlebot4_gz_bringup turtlebot4_gz.launch.py
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related
      - ./turtlebot4-simulation/gazebo_data:/root/.gazebo:rw       # Persist Gazebo downloads/models
    depends_on:
      - turtlebot4-discovery

  turtlebot4-control:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-control:jazzy
    command: ros2 launch turtlebot4_viz view_navigation.launch.py slam:=true nav2:=true rviz:=true
    # command: ros2 launch turtlebot4_navigation nav2.launch.py
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related
    depends_on:
      - turtlebot4-discovery